# Generated by Django 2.1 on 2020-11-20 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.EmailField(max_length=30)),
                ('receivers', models.CharField(max_length=100)),
                ('cc', models.CharField(max_length=100, null=True)),
                ('bcc', models.CharField(max_length=100, null=True)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('is_success', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'email_service',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=50)),
                ('file_path', models.FilePathField(path='/EmailService/EmailService/static/uploaded_files/')),
            ],
            options={
                'db_table': 'email_file',
            },
        ),
        migrations.AddField(
            model_name='email',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmailService.File'),
        ),
    ]
